In [1]:
import numpy as np

In [4]:
#                      numero de elementos
one_dimension_arr = np.arange(10)
# rango de elementos del 0 al 9
one_dimension_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Trae todos los elementos con un salto de 2
one_dimension_arr[::2]

array([0, 2, 4, 6, 8])

In [10]:
# Trae los elementos desde la posición 3 hasta la posición 5, sin tomar esta ultima en cuenta ([i:j-1])
one_dimension_arr[3:5]

array([3, 4])

In [12]:
# Trae los elementos desde el inicion del arreglo, hasta la posición 8, sin tomar esta ultima en cuenta, en saltos de 2
one_dimension_arr[:8:2]

array([0, 2, 4, 6])

In [14]:
# Trae los elementos desde la posición 1 hasta el final del array, en saltos de 3 (i+3)
one_dimension_arr[1::3]

array([1, 4, 7])

In [17]:
# Trae los elementos desde la posición 7 hasta el inicio del array (pasos en -1)
one_dimension_arr[7::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
lista_indices = [5, 6, 7]
one_dimension_arr[lista_indices]

array([5, 6, 7])

In [21]:
random_generator_seed = np.random.default_rng(234444)

In [25]:
low = 0
high = 10
size = (3, 4)
two_dimension_arr = random_generator_seed.uniform(low=low, high=high, size=size)
two_dimension_arr

array([[7.70576691, 5.3900531 , 1.26516957, 7.58848631],
       [7.61290526, 9.92326006, 9.1511299 , 0.10048282],
       [3.64120972, 6.95888084, 1.38819387, 0.64277152]])

In [31]:
two_dimension_arr[1:, :]

array([[7.61290526, 9.92326006, 9.1511299 , 0.10048282],
       [3.64120972, 6.95888084, 1.38819387, 0.64277152]])

In [32]:
# Devuelve las filas del arreglo en base a los indices ingresados
index_list = [0, 2, 1, 0]
two_dimension_arr[index_list]

array([[7.70576691, 5.3900531 , 1.26516957, 7.58848631],
       [3.64120972, 6.95888084, 1.38819387, 0.64277152],
       [7.61290526, 9.92326006, 9.1511299 , 0.10048282],
       [7.70576691, 5.3900531 , 1.26516957, 7.58848631]])

In [33]:
# Compara los elementos del arreglo, y devuelve el arreglo con una respuesta booleana por cada comparación
mask_great_5 = two_dimension_arr > 5
mask_great_5

array([[ True,  True, False,  True],
       [ True,  True,  True, False],
       [False,  True, False, False]])

In [34]:
# Trae solo los elementos que cumplan la condición dada
two_dimension_arr[mask_great_5]


array([7.70576691, 5.3900531 , 7.58848631, 7.61290526, 9.92326006,
       9.1511299 , 6.95888084])