In [1]:
import numpy as np

In [2]:
python_list = [1, 2, 3, 4, 5, 6]
arr = np.array(python_list)
print(arr)

[1 2 3 4 5 6]


In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((10, 2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [5]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [6]:
random_generator = np.random.default_rng()

In [7]:
random_generator.normal(loc=0,scale=1,size=12)

array([ 1.03122185,  0.80096122, -0.17045185, -1.7066703 , -0.86944282,
       -2.40960957,  0.39983483,  0.23276766, -0.15838271, -0.00736463,
        0.5681663 ,  0.62512315])

In [8]:
random_generator.normal(loc=0,scale=1,size=12)

array([ 7.12663036e-04, -6.63038589e-01, -2.17666786e-01, -3.91698710e-01,
       -6.96807152e-01, -1.18249983e+00,  7.29575481e-01, -5.69804471e-01,
        2.80826714e+00,  1.16728198e-02,  8.23836593e-01,  4.47308058e-02])

In [16]:
random_generator.normal(loc=0,scale=1,size=30)


array([-0.54296461,  0.39439296,  0.50223383,  0.39144478,  0.68083816,
        0.42209455,  1.41416727,  0.51402059,  0.51640858,  0.4884509 ,
        0.63625513, -1.06539156,  0.03288262,  0.35270728,  0.61151806,
       -0.20282683, -0.95334769,  1.65875647,  0.19208482,  0.28418954,
       -0.13658442, -2.76549936,  1.21420347, -1.16434587, -1.47353094,
       -0.55507398,  2.39088121, -1.43966149,  0.76052208, -0.64672883])